modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mp"
version="4.1.0"
displayName="Minecraft Plus"
credits="I made this mod"
displayURL="https://example.com"
authors="EndingOsprey317"

[[dependencies.mp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




